<a href="https://colab.research.google.com/github/Aarya-Musale/Machine-Learning/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing

- Data preprocessing is a process of preparing the raw data and making it suitable for a machine learning model. It is the first and crucial step while creating a machine learning model.



- When creating a machine learning project, it is not always a case that we come across the clean and formatted data.



- And while doing any operation with data, it is mandatory to clean it and put in a formatted way. So for this, we use data preprocessing task.

# What is the need of Data Preprocessing?

o A real-world data generally contains noises, missing values, and maybe in an unusable format which cannot be directly used for machine learning models.


o Data preprocessing is required tasks for cleaning the data and making it suitable for a machine learning model which also increases the accuracy and efficiency of a machine learning model.

#### It involves below steps:

    Getting the dataset
    Importing libraries
    Importing datasets
    Finding Missing Data
    Encoding Categorical Data
    Splitting dataset into training and test set
    Feature scaling

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#country , age and salary
data = [['India',38.0,np.nan],
    ['France',43.0,45000.0],
 ['Germany',30.0, 54000.0],
 ['France' ,48.0, 65000.0],
 ['Germany' ,40.0, np.nan],
 ['India' ,35.0, 58000.0],
 ['Germany', np.nan ,53000.0],
 ['France' ,49.0, 79000.0],
 ['India', 50.0 ,88000.0],
 ['France' ,np.nan, 77000.0]]

In [ ]:
df = pd.DataFrame(data)
df  # NaN- Not a Number

         0     1        2
0    India  38.0      NaN
1   France  43.0  45000.0
2  Germany  30.0  54000.0
3   France  48.0  65000.0
4  Germany  40.0      NaN
5    India  35.0  58000.0
6  Germany   NaN  53000.0
7   France  49.0  79000.0
8    India  50.0  88000.0
9   France   NaN  77000.0

In [ ]:
# create csv file of above df
df.to_csv('sample.csv',index=False)

In [ ]:
#Asisignment -  check df.to_numpy(), df.to_dict(), df.to_excel(),df.to_json()

NaN is Not A Number means that particular cell is missing

In [ ]:
#Assignment: check library missingno
# Plot the NaN present in your dataset

# 3 ways to plot missing values
# missingno library
# bar plot
# heatmap

In [ ]:
# To deal with missing values either u drop them
# You can handle them

In [ ]:
# age data
a_age = df[1].mean() # average age
#df[1].fillna(25)
df[1].fillna(a_age)

0    38.000
1    43.000
2    30.000
3    48.000
4    40.000
5    35.000
6    41.625
7    49.000
8    50.000
9    41.625
Name: 1, dtype: float64

In [ ]:
# use bfill (backward filling) or ffill (forward filling)
df[1].fillna(method='bfill')

/tmp/ipykernel_601/1703510876.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[1].fillna(method='bfill')

0    38.0
1    43.0
2    30.0
3    48.0
4    40.0
5    35.0
6    49.0
7    49.0
8    50.0
9     NaN
Name: 1, dtype: float64

**Preprocessing using scikit learn**

We perform 2 steps
1. fit()
2. transform()
--------------------
fit_transform()

High Low Mid - a-z
 0    1   2

High 0
Mid 2
Low 1
Low 1
High 0

## Example:

Sample data:
Male
Female
Male
Female
Female
Other
Male
Male

step 1:
fit()-- used for training  [f,m,o] ->     0 1 2

step 2:          
conversion process we carry using transform() method

#1. Single file --> fit_transform()

#2. Train.csv--fit_transform() | Test.csv-- transform()

# Encoding Categorical data:

- Categorical data is data which has some categories such as,  Country


- Since machine learning model completely works on mathematics and numbers, but if our dataset would have a categorical variable, then it may create trouble while building the model. So it is necessary to encode these categorical variables into numbers.

### **Process of Converting the Categorical Data into number is called as Encoding**

Categorical-
1. Nominal Data- ordering is nt imp. Gender, Fruits, Disease, Car model
2. Ordinal Data- ordering is imp. Qualification, Review

In [ ]:
df[0]

In [ ]:
df[0].unique()

Categorical data is of 2 types:

    -Nominal data (where sequence order doesnt matter)
     Ex. Male/Female, CountryNames, ColorNames, VehicleName , ObjectNames

    - Ordinal data (where sequence order matters)
    Ex. Result, Rank, EducationLevel,Rating

In [ ]:
# using replace({old_value:new_value/number}): this is a TEMP conversion
df[0].replace({'India':1,'France':2,'Germany':3})

/tmp/ipykernel_601/2382496367.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[0].replace({'India':1,'France':2,'Germany':3})

0    1
1    2
2    3
3    2
4    3
5    1
6    3
7    2
8    1
9    2
Name: 0, dtype: int64

In [ ]:
# using map
df[0].map({'India':1,'France':2,'Germany':3})

0    1
1    2
2    3
3    2
4    3
5    1
6    3
7    2
8    1
9    2
Name: 0, dtype: int64

# sklearn.preprocessing

## Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()
#lets supply country data present at 0 index
lb.fit_transform(df[0])
#in above case labelencoder converted India as 2, France as 0 and germany as 1

array([2, 0, 1, 0, 1, 2, 1, 0, 2, 0])

In [ ]:
df[0].values

array(['India', 'France', 'Germany', 'France', 'Germany', 'India',
       'Germany', 'France', 'India', 'France'], dtype=object)

In [ ]:
lb.classes_
#LabelEncoder follows Alphabatic order a-z

array(['France', 'Germany', 'India'], dtype=object)

In [ ]:
vj = ['Germany','India','India','France','Germany','India']
vj

['Germany', 'India', 'India', 'France', 'Germany', 'India']

In [ ]:
# convert vj to number
lb.transform(vj)

array([1, 2, 2, 0, 1, 2])

In [ ]:
lb.transform(['India','France','India'])

array([2, 0, 2])

In [ ]:
g = pd.DataFrame({'gender':['male','female','female','male','male','female'],
             'cat':['A','A','A','B','C','C']})
g

   gender cat
0    male   A
1  female   A
2  female   A
3    male   B
4    male   C
5  female   C

In [ ]:
lb2 = LabelEncoder()
#labelEncode accepts only 1D data
lb2.fit(g['gender'])

LabelEncoder()

In [ ]:
lb2.classes_

array(['female', 'male'], dtype=object)

In [ ]:
lb2.transform(g.gender) # converted

array([1, 0, 0, 1, 1, 0])

In [ ]:
g.gender.values  # Actual values

array(['male', 'female', 'female', 'male', 'male', 'female'], dtype=object)

In [ ]:
lb2.classes_

array(['female', 'male'], dtype=object)

In [ ]:
g.columns

Index(['gender', 'cat'], dtype='object')

In [ ]:
for col in g.columns:
    g['new_'+col] = lb2.fit_transform(g[col])  # add new transformed columns

In [ ]:
g

   gender cat  new_gender  new_cat
0    male   A           1        0
1  female   A           0        0
2  female   A           0        0
3    male   B           1        1
4    male   C           1        2
5  female   C           0        2

In [ ]:
# i will use titanic dataset
# in which we have sex column will convert Male and Female in 1 and 0
import seaborn as sns
t = sns.load_dataset('titanic')
t[:3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [ ]:
t['sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
#use lb2 to convert above series into 0 &1
t['sex'] = lb2.fit_transform(t['sex'])

In [ ]:
t[:2]

In [ ]:
k = ['male','female','male','female']
k

In [ ]:
lb2 # already trained over male female data

In [ ]:
# next step is to convert k values to 0 , 1
lb2.transform(k)

In [ ]:
new_data= [1,1,1,1,1,0,0,0,0,0,1,0,1,1,1,0,0,1,1,0,1]
new_data

In [ ]:
lb2.classes_

In [ ]:
#Convert above 0 & 1 into Category male and female
lb2.inverse_transform(new_data)

In [ ]:
t[:6]

In [ ]:
t['embarked'].unique()

In [ ]:
# Asisgnment:
#1. Select embarked,class,embark_town and apply Label encoder --> replace these columns with numeric value

In [ ]:
# Interview question:
# What are different ways to deal with Categorical data?
# How to perform encoding in ML?
# How to convert categorical data using pandas
# how to convert categorical data using sklearn.preprocessing

# Dummy Variables:

- Dummy variables are those variables which have values 0 or 1.


- The 1 value gives the presence of that variable in a particular column, and rest variables become 0.


- With dummy encoding, we will have a number of columns equal to the number of categories.

In [ ]:
# fruits column         Apple | Banana | Mango
# Mango                        0           0                1
# Apple                          1           0                0
# Banana                       0           1                0

In [ ]:
import pandas as pd

place = pd.DataFrame({'data':['Katraj','Camp','Hadapsar','Katraj','Katraj','Hadapsar','Camp','Camp','Hadapsar']})
place

In [ ]:
place.data.unique()

#### Wherever we have categorical data ina column, there u have to apply OneHotEncoder

In [ ]:
#Encoding for dummy variables using OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ob = OneHotEncoder()

In [ ]:
ob

In [ ]:
place.shape

FOr the preprocessing we have 3 options
1. fit() - for training only
2. transform()- for conversion
3. fit_transform()- for training + conversion

In [ ]:
convert = ob.fit_transform(place)
convert
#return sparse matrix

In [ ]:
final = convert.toarray()
final

In [ ]:
place.values

In [ ]:
#check the sequence of conversion==> it follows A-Z order
ob.categories_

#once we get converted category into columns
#then next step is to add thse conversions in original dataframe

In [ ]:
ob.categories_[0]

In [ ]:
#convert final into dataFrame
fin = pd.DataFrame(final,columns=ob.categories_[0],dtype=int)
fin

In [ ]:
# will add above new df into old one
d1 = pd.concat([place,fin],axis=1)
d1[:2]

In [ ]:
d1.drop(columns='data',inplace=True)

In [ ]:
d1

In [ ]:
ob.categories_

In [ ]:
#rename columns 0,1,2 ==> Camp Hadpsar Katraj
#d1.columns= ob.categories_

In [ ]:
d1

In [ ]:
ob

In [ ]:
plc = input('Enter the place:')
new = ob.transform([[plc]])
new.toarray()

In [ ]:
import pickle
ob_mode = open('ob.pkl','wb')
pickle.dump(ob,ob_mode)

In [ ]:
import pickle
# read pkl file
ob_mode = open('ob.pkl','rb')
ob_new = pickle.load(ob_mode)

In [ ]:
plc = input('Enter the place:')
try:
  print(ob_new.transform([[plc]]).toarray())
except:
  print('Please enter Camp/Katraj/Hadpsar')

## Using pandas: get_dummies()

#### alternative option and simple option to OneHot is get_dummies() of pandas

In [ ]:
place

In [ ]:
pd.get_dummies(place,dtype=int)

In [ ]:
#model.predict([0,1,0])

https://pythonsimplified.com/difference-between-onehotencoder-and-get_dummies/

In [ ]:
# IMP interview questions-
#How to deal with categorical data?
# WHat are different encoding techniques?
# difference btween onehot and get_dummies?
# what is dummy variable trap?

# Feature Scaling

- Feature scaling is the final step of data preprocessing in machine learning.


- It is a technique to standardize the independent variables of the dataset in a specific range.


- In feature scaling, we put our variables in the same range and in the same scale so that no any variable dominate the other variable.

#age = 30,40,50
#salary = 65000,56000,150000,240000

### There are 2 types:
    - Standardization x-M(mue/meanofX)/sigma (std deviation) ---> StandardScalar--> for classification
    - Normalization x- min(x)/(max(x)-min(x)) --> MinMaxScalar--> for Regression

Q. Standardization vs Normalization?

Q. StandardScalar vs Normalizer?

### StandardScaler

In [ ]:
# StandardScaler   # x -mean(total_x)/std(total_x) -3 0 +3

In [ ]:
#load boston_housing dataset
import numpy as np
import pandas as pd

df = pd.read_csv('boston.csv')
df.head(2)

In [ ]:
df.describe().T

In [ ]:
#load StandardScalar(standardization)
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
sc

In [ ]:
df.shape

In [ ]:
new = sc.fit_transform(df)
new

In [ ]:
import numpy as np
data = [20,100,34,500,340,200,1,3,5,4500]
# sc = x - mean(data)/std(data)
m = np.mean(data)
s = np.std(data)
#m,s
(1600-m)/s

In [ ]:
new.shape

In [ ]:
sc.mean_

In [ ]:
sc.n_features_in_

In [ ]:
#lets convert  new to df
ndf = pd.DataFrame(new)
ndf.head(2)

In [ ]:
df.head(2)

In [ ]:
# check outlliers
import seaborn as sns
sns.boxplot(data=ndf)

In [ ]:
ndf.describe().T

In [ ]:
#now lets check hist plot of both
#df
df.CRIM.plot.hist()

In [ ]:
ndf[0].plot.hist()

### MinMaxScaler

In [ ]:
# MinMaxScaler  # x- min()/(max()-min())
#range of minMax scalar is 0 to 1

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mx = MinMaxScaler()
norm = mx.fit_transform(df)
normdf = pd.DataFrame(norm)
normdf

In [ ]:
normdf.describe().T

In [ ]:
normdf[7].plot.hist()

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
#df['target']  # its a regression problem

In [ ]:
# input and ouput
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
knn = KNeighborsRegressor()
knn.fit(x,y)  # data without scaling
knn.score(x,y)*100

In [ ]:
X_n = ndf.iloc[:,:-1]
X_n.shape

In [ ]:
knn2 = KNeighborsRegressor()
knn2.fit(X_n,y)  # data with scaling
knn2.score(X_n,y)*100